---
- hosts: localhost
  connection: local
  become: true

  tasks:

### INSTALL GNOME TWEAKS AND EXTENSIONS

  - name: Extensions | install gnome tweaks
    apt:
      name:
        - gnome-shell-extensions
        - gnome-tweaks
        - dbus-x11
        - python3-pip
      state: latest
    pip3:
      name:
        - gnome-extensions-cli
      state: latest

  - name: Extensiopns | install 
    script: "./files/extensions/gnome-extensions.py"

  # - name: Extensions | copy extensions locally
  #   copy:
  #     src: files/extensions/{{ item }}
  #     dest: /home/mattia/.local/share/gnome-shell/extensions/{{ item }}
  #     owner: mattia
  #     group: mattia
  #   with_items:
  #     - gnome-ui-tune@itstime.tech
  #     - bluetooth-quick-connect@bjarosze.gmail.com
  #     - emoji-selector@maestroschan.fr
  #     - Vitals@CoreCoding.com

### SET PREFERENCES ###

  - name: Preferences | set dark theme ##didn't work
    # become_user: mattia
    shell: "gsettings set org.gnome.desktop.interface color-scheme prefer-dark"
    register: command_output

  - debug:
      var: command_output.stdout_lines
  - debug:
      var: command_output.stderr_lines

### SET KEYBINDINGS ###  

  - name: Keybindings | file browser
    become_user: mattia
    dconf:
      key: "/org/gnome/settings-daemon/plugins/media-keys/home"
      value: "['<Super>f']"

  - name: Keybindings | web browser
    become_user: mattia
    dconf:
      key: "/org/gnome/settings-daemon/plugins/media-keys/www"
      value: "['<Super>b']"

  - name: Keybindings | calculator browser
    become_user: mattia
    dconf:
      key: "/org/gnome/settings-daemon/plugins/media-keys/calculator"
      value: "['<Super>c']"

  - name: Keybindings | terminal shortcut name
    become_user: mattia
    dconf:
      key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name"
      value: "'terminal'"

  - name: Keybindings | terminal shortcut command
    become_user: mattia
    dconf:
      key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command"
      value: "'gnome-terminal'"
  
  - name: Keybindings | terminal shortcut binding
    become_user: mattia
    dconf:
      key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding"
      value: "'<Super>t'"

  - name: Keybindings | enable custom keybindings
    become_user: mattia
    dconf:
      key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
      value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']"
