---
- hosts: localhost
  connection: local
  become: true

  # roles:
  #   - role: ansible-gnome-extensions
  #     vars:
  #       gnome_extension_ids:
  #         - 8
  tasks:

### INSTALL GNOME TWEAKS AND EXTENSIONS

  - name: Extensions | install gnome tweaks
    apt:
      name:
        - gnome-shell-extensions
        - gnome-tweaks
        - dbus-x11
        - python3-pip
      state: latest
    
  - name: Extensions | install pip3 gext 
    pip:
      name:
        - gnome-extensions-cli
      state: latest
      extra_args: --break-system-packages

  - name: Extensions | install 
    become_user: mattia
    shell: "gext install gnome-ui-tune@itstime.tech bluetooth-quick-connect@bjarosze.gmail.com emoji-selector@maestroschan.fr Vitals@CoreCoding.com"

  - name: Extensions | restart shell
    shell: killall -3 gnome-shell

  - name: Extensions | enable 
    become_user: mattia
    shell: "gext enable gnome-ui-tune@itstime.tech bluetooth-quick-connect@bjarosze.gmail.com emoji-selector@maestroschan.fr Vitals@CoreCoding.com"

### SET PREFERENCES ###

  - name: Preferences | set dark theme ##didn't work
    become_user: mattia
    dconf:
      key: "/org/gnome/desktop/interface/color-scheme"
      value: "'prefer-dark'"

### SET KEYBINDINGS ### 

  # - name: Keybindings | file browser
  #   become_user: mattia
  #   dconf:
  #     key: "/org/gnome/settings-daemon/plugins/media-keys/home"
  #     value: "['<Super>f']"

  # - name: Keybindings | web browser
  #   become_user: mattia
  #   dconf:
  #     key: "/org/gnome/settings-daemon/plugins/media-keys/www"
  #     value: "['<Super>b']"

  # - name: Keybindings | calculator browser
  #   become_user: mattia
  #   dconf:
  #     key: "/org/gnome/settings-daemon/plugins/media-keys/calculator"
  #     value: "['<Super>c']"

  # - name: Keybindings | terminal shortcut name
  #   become_user: mattia
  #   dconf:
  #     key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name"
  #     value: "'terminal'"

  # - name: Keybindings | terminal shortcut command
  #   become_user: mattia
  #   dconf:
  #     key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command"
  #     value: "'gnome-terminal'"
  
  # - name: Keybindings | terminal shortcut binding
  #   become_user: mattia
  #   dconf:
  #     key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding"
  #     value: "'<Super>t'"

  # - name: Keybindings | enable custom keybindings
  #   become_user: mattia
  #   dconf:
  #     key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
  #     value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']"
