---
- hosts: localhost
  connection: local
  become: true

  tasks:
  
### PERFORM UPDATE && UPGRADE ###

  - name: apt Update & Upgrade
    apt:
      upgrade: yes
      update_cache: 'yes'

### INSTALL DEFAULT PACKAGES ###

  - name: Install must-have packages
    package:
      name: 
        - htop
        - python3-psutil
        - nano
        - curl
        - wget
        - neofetch
        - ranger
        - gparted

  - name: Install Brave Browser 1/3
    shell: 'curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg'
    
  - name: Install Brave Browser 2/3
    shell: 'echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main"|sudo tee /etc/apt/sources.list.d/brave-browser-release.list'
  
  - name: Install Brave Browser 3/3
    apt:
      update_cache: 'yes'
      name:
        - brave-browser

### COPY DOTFILES ###

  - name: Copy .bashrc config
    copy:
      src: files/bashrc
      dest: /home/mattia/.bashrc
      owner: mattia
      group: mattia

  - name: Copy dotfiles
    copy:
      src: files/config_dotfiles/
      dest: /home/mattia/.config/
      owner: mattia
      group: mattia

### CREATE COMMON LOCATIONS ###
  
  - name: Create Github folder
    become_user: mattia
    file:
      path: /home/mattia/Documents/GitHub
      state: directory