---
- hosts: localhost
  connection: local
  become: true

  tasks:
  
  - name: apt Update & Upgrade
    apt:
      upgrade: yes
      update_cache: 'yes'

  - name: Copy .bashrc config
    copy:
      src: files/bashrc
      dest: /home/mattia/.bashrc
      owner: mattia
      group: mattia

  - name: Install monitoring packages
    package:
      name: 
        - htop
        - python3-psutil
        - nano
        - curl
        - wget
        - neofetch

  - name: Copy dotfiles
    copy:
      src: files/config_dotfiles/*
      dest: /home/mattia/.config/
      owner: mattia
      group: mattia
  
  - name: Create Github folder
    become_user: mattia
    file:
      path: /home/mattia/Documents/GitHub
      state: directory

  - name: Use RTC time for dual boot
    shell: "timedatectl set-local-rtc 1 --adjust-system-clock"