---
- hosts: localhost
  connection: local
  become: true

  tasks:
  
### PERFORM UPDATE && UPGRADE ###

  - name: apt Update & Upgrade
    apt:
      upgrade: yes
      update_cache: 'yes'

### INSTALL DEFAULT PACKAGES ###

  - name: Install must-have packages
    package:
      name: 
        - htop
        - python3-psutil
        - nano
        - curl
        - wget
        - neofetch
        - ranger

### COPY DOTFILES ###

  - name: Copy .bashrc config
    copy:
      src: files/bashrc
      dest: /home/mattia/.bashrc
      owner: mattia
      group: mattia

  - name: Copy dotfiles
    copy:
      src: files/config_dotfiles/
      dest: /home/mattia/.config/
      owner: mattia
      group: mattia

### CREATE COMMON LOCATIONS ###
  
  - name: Create Github folder
    become_user: mattia
    file:
      path: /home/mattia/Documents/GitHub
      state: directory